# Generated by Django 5.1.5 on 2025-07-04 16:44

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChargingStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("charging_speed", models.FloatField()),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("battery_capacity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("year_of_manufacture", models.IntegerField()),
                ("battery_capacity", models.FloatField()),
                ("consumption_rate", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="TestInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "charging_stops",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=101),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("avg_distance_diff", models.FloatField()),
                ("avg_time_diff", models.FloatField()),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="graphs.test"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_city", models.CharField(max_length=200)),
                ("end_city", models.CharField(max_length=200)),
                ("start_coord", models.CharField(max_length=100)),
                ("end_coord", models.CharField(max_length=100)),
                ("osrm_accumulated_routes", models.TextField()),
                ("osrm_total_time", models.IntegerField()),
                ("osrm_total_distance", models.IntegerField()),
                (
                    "my_accumulated_routes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list, size=None
                    ),
                ),
                (
                    "my_accumulated_charging_stops",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "my_accumulated_empty_battery",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("my_total_distance", models.IntegerField()),
                ("my_total_time", models.IntegerField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["start_city", "end_city"],
                        name="graphs_test_start_c_385e00_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TestInstanceRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "new_accumulated_routes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list, size=None
                    ),
                ),
                (
                    "new_accumulated_charging_stops",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("new_total_distance", models.FloatField()),
                ("new_total_time", models.FloatField()),
                (
                    "test_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="graphs.testinstance",
                    ),
                ),
                (
                    "test_route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="graphs.testroute",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_city", models.CharField(max_length=100)),
                ("end_city", models.CharField(max_length=100)),
                ("total_distance", models.IntegerField(null=True)),
                ("total_travel_time", models.IntegerField(null=True)),
                ("total_consumption", models.IntegerField(null=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="graphs.vehicle"
                    ),
                ),
            ],
        ),
    ]
