# Generated by Django 5.1.5 on 2025-03-31 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0002_chargingstation_vehicle_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="end_city",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="route",
            name="start_city",
            field=models.CharField(default="2", max_length=100),
            preserve_default=False,
        ),
    ]
