# Generated by Django 5.1.5 on 2025-04-24 12:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0003_route_end_city_route_start_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="distance",
        ),
        migrations.RemoveField(
            model_name="route",
            name="end",
        ),
        migrations.RemoveField(
            model_name="route",
            name="start",
        ),
        migrations.RemoveField(
            model_name="route",
            name="waypoints",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="current_battery",
        ),
        migrations.AddField(
            model_name="route",
            name="total_distance",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="route",
            name="total_travel_time",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="year_of_manufacture",
            field=models.IntegerField(default="2000"),
            preserve_default=False,
        ),
    ]
