# Generated by Django 5.1.5 on 2025-04-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0004_remove_route_distance_remove_route_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="total_consumption",
            field=models.IntegerField(null=True),
        ),
    ]
