# Generated by Django 5.1.5 on 2025-05-21 06:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0005_route_total_consumption"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="location",
        ),
        migrations.RemoveField(
            model_name="test",
            name="name",
        ),
        migrations.AddField(
            model_name="test",
            name="cities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(), blank=True, default=list, size=None
            ),
        ),
        migrations.CreateModel(
            name="TestRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_city", models.CharField(max_length=100)),
                ("end_city", models.CharField(max_length=100)),
                (
                    "osrm_accumulated_routes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("osrm_total_time", models.IntegerField(null=True)),
                ("osrm_total_distance", models.IntegerField(null=True)),
                (
                    "my_accumulated_routes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "my_accumulated_charging_stops",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("my_total_distance", models.IntegerField(null=True)),
                ("my_total_time", models.IntegerField(null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["start_city", "end_city"],
                        name="graphs_test_start_c_385e00_idx",
                    )
                ],
                "unique_together": {("start_city", "end_city")},
            },
        ),
    ]
