# Generated by Django 5.1.5 on 2025-05-21 07:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0006_remove_test_location_remove_test_name_test_cities_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testroute",
            name="osrm_accumulated_routes",
        ),
        migrations.AlterField(
            model_name="testroute",
            name="end_city",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="testroute",
            name="my_accumulated_routes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="testroute",
            name="my_total_distance",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="testroute",
            name="my_total_time",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="testroute",
            name="osrm_total_distance",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="testroute",
            name="osrm_total_time",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="testroute",
            name="start_city",
            field=models.CharField(max_length=200),
        ),
    ]
