# Generated by Django 5.1.5 on 2025-05-21 08:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0007_remove_testroute_osrm_accumulated_routes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testroute",
            name="my_accumulated_charging_stops",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
