# Generated by Django 5.1.5 on 2025-05-21 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0008_alter_testroute_my_accumulated_charging_stops"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestRoute",
        ),
    ]
