# Generated by Django 5.1.5 on 2025-05-21 08:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0009_delete_testroute"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_city", models.CharField(max_length=200)),
                ("end_city", models.CharField(max_length=200)),
                ("osrm_total_time", models.IntegerField()),
                ("osrm_total_distance", models.IntegerField()),
                (
                    "my_accumulated_routes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list, size=None
                    ),
                ),
                (
                    "my_accumulated_charging_stops",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("my_total_distance", models.IntegerField()),
                ("my_total_time", models.IntegerField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["start_city", "end_city"],
                        name="graphs_test_start_c_385e00_idx",
                    )
                ],
                "unique_together": {("start_city", "end_city")},
            },
        ),
    ]
