# Generated by Django 5.1.5 on 2025-05-21 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0010_testroute"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testroute",
            name="my_accumulated_charging_stops",
        ),
        migrations.RemoveField(
            model_name="testroute",
            name="my_accumulated_routes",
        ),
    ]
