# Generated by Django 5.1.5 on 2025-05-21 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0011_remove_testroute_my_accumulated_charging_stops_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="testroute",
            name="graphs_test_start_c_385e00_idx",
        ),
        migrations.AlterUniqueTogether(
            name="testroute",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="testroute",
            name="osrm_accumulated_routes",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
