# Generated by Django 5.1.5 on 2025-05-21 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0012_remove_testroute_graphs_test_start_c_385e00_idx_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestRoute",
        ),
    ]
