# Generated by Django 5.1.5 on 2025-05-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0013_delete_testroute"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_city", models.CharField(max_length=200)),
                ("end_city", models.CharField(max_length=200)),
                ("osrm_accumulated_routes", models.TextField()),
                ("osrm_total_time", models.IntegerField()),
                ("osrm_total_distance", models.IntegerField()),
                ("my_total_distance", models.IntegerField()),
                ("my_total_time", models.IntegerField()),
            ],
        ),
    ]
