# Generated by Django 5.1.5 on 2025-05-21 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0014_testroute"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestRoute",
        ),
    ]
