# Generated by Django 5.1.5 on 2025-05-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0016_testroute"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
        migrations.AddIndex(
            model_name="testroute",
            index=models.Index(
                fields=["start_city", "end_city"], name="graphs_test_start_c_385e00_idx"
            ),
        ),
    ]
