# Generated by Django 5.1.5 on 2025-05-21 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0017_delete_test_testroute_graphs_test_start_c_385e00_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="testroute",
            name="end_coord",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testroute",
            name="start_coord",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
