# Generated by Django 5.1.5 on 2025-05-22 16:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0019_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="testroute",
            name="my_accumulated_empty_battery",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
