# Generated by Django 5.1.5 on 2025-05-25 11:57

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0020_testroute_my_accumulated_empty_battery"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "charging_stops",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="graphs.test"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestInstanceRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "new_accumulated_routes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list, size=None
                    ),
                ),
                (
                    "new_accumulated_charging_stops",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("new_total_distance", models.IntegerField()),
                ("new_total_time", models.IntegerField()),
                (
                    "test_route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="graphs.testroute",
                    ),
                ),
            ],
        ),
    ]
