# Generated by Django 5.1.5 on 2025-05-27 08:48

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0021_testinstance_testinstanceroute"),
    ]

    operations = [
        migrations.AddField(
            model_name="testinstance",
            name="avg_distance_diff",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testinstance",
            name="avg_time_diff",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testinstanceroute",
            name="test_instance",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="graphs.testinstance",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="testinstance",
            name="charging_stops",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
