# Generated by Django 5.1.5 on 2025-05-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0022_testinstance_avg_distance_diff_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testinstance",
            name="avg_distance_diff",
        ),
        migrations.RemoveField(
            model_name="testinstance",
            name="avg_time_diff",
        ),
    ]
