# Generated by Django 5.1.5 on 2025-05-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0023_remove_testinstance_avg_distance_diff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testinstanceroute",
            name="new_total_distance",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="testinstanceroute",
            name="new_total_time",
            field=models.FloatField(),
        ),
    ]
