# Generated by Django 5.1.5 on 2025-05-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0024_alter_testinstanceroute_new_total_distance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testinstance",
            name="avg_distance_diff",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testinstance",
            name="avg_time_diff",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
