# Generated by Django 5.1.5 on 2025-06-10 19:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0025_testinstance_avg_distance_diff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testinstanceroute",
            name="additional_charging_stations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100), default=list, size=None
            ),
        ),
    ]
