# Generated by Django 5.1.5 on 2025-06-10 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0026_testinstanceroute_additional_charging_stations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testinstanceroute",
            name="additional_charging_stations",
        ),
    ]
